@token = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzY290dGlsZW9uYXJkbzFAZ21haWwuY29tIiwiaWRfY29uZG9taW5pbyI6MTQsInRpcG9fcGVyZmlsIjoiTU9SQURPUiIsImlhdCI6MTc3ODg2NjM5MywiZXhwIjoxNzc4OTUyNzkzfQ.NYUDr8Kuj5BUi_89yx0D-uyWcdDmeGnxjrdXkDP8GpM
### LoginCondominium
# @name loginRequest
POST http://localhost:8080/api/v1/auth/login/condominium
Content-Type: application/json

{
  "email": "teste7@teste.com",
  "password": "testeapi123"
}

### LoginResident
# @name loginRequest
POST http://localhost:8080/api/v1/auth/login/resident
Content-Type: application/json

{
"email": "machado.breno127@gmail.com",
"password": "18IF$wl#"
}


### ME - CONDOMINIUM
# @name meCondominium
GET http://localhost:8080/api/v1/auth/me/condominium
Authorization: Bearer {{token}}

### ME - RESIDENT
# @name meResident
GET http://localhost:8080/api/v1/auth/me/resident
Authorization: Bearer {{token}}



### ===== CONDOMINIUM =====
# @name listCondominium
GET https://api-vizinhanca.onrender.com/api/v1/condominium
Authorization: Bearer {{token}}

### Search by condominium
# @name searchResidentsByCondominium
GET https://api-vizinhanca.onrender.com/api/v1/condominium/resident/me
Authorization: Bearer {{token}}

### Search activities by condominium
# @name searchActivitiesByCondominium
GET https://api-vizinhanca.onrender.com/api/v1/condominium/activity/me
Authorization: Bearer {{token}}

### Search by id
# @name searchCondominium
GET https://api-vizinhanca.onrender.com/api/v1/condominium/9
Authorization: Bearer {{token}}

### Insert
# @name insertCondominium
POST https://api-vizinhanca.onrender.com/api/v1/condominium
Content-Type: application/json

{
  "name": "TESTE CONDOMÍNIO",
  "cnpj": "12345678910122",
  "amount_blocks": 4,
  "amount_apartments": 160,
  "email": "teste8@teste.com",
  "password": "testeapi123",
  "address": {
    "cep": "01310100",
    "street": "Avenida Paulista",
    "neighborhood": "Bela Vista",
    "number": "1000",
    "landmark": "Próximo ao MASP",
    "city": "São Paulo",
    "state": "SP"
  }
}

### Update
# @name updateCondominium
PUT https://api-vizinhanca.onrender.com/api/v1/condominium/7
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Bela Vista",
  "cnpj": "12345678910124",
  "amount_blocks": 4,
  "amount_apartments": 160,
  "email": "contato@scotti.com.br"
}

### Delete
# @name deleteCondominium
DELETE https://api-vizinhanca.onrender.com/api/v1/condominium/11
Authorization: Bearer {{token}}


### ===== RESIDENT =====
# @name listResident
GET https://api-vizinhanca.onrender.com/api/v1/resident
Authorization: Bearer {{token}}

### Search by id
# @name searchResident
GET https://api-vizinhanca.onrender.com/api/v1/resident/6
Authorization: Bearer {{token}}

### Insert
# @name insertResident
POST https://api-vizinhanca.onrender.com/api/v1/resident
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "photo": "",
  "name": "Teste - SCOTTI",
  "apartment": "4",
  "block": "Torre 4",
  "cpf": "45678912340",
  "email": "scottileonardo1@gmail.com",
  "phone": "11998572585",
  "score": 0,
  "condominium_id": 14
}

### Update
# @name updateResident
PUT http://localhost:8080/api/v1/resident/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "foto": "",
  "nome": "Giovana - TESTE",
  "apto": "22",
  "bloco": "B",
  "cpf": "67890123456",
  "email": "ricardo.santos@yahoo.com",
  "telefone": "11904851846",
  "pontuacao": 0,
  "condominium_id": 8
}

### Delete
# @name deleteResident
DELETE https://api-vizinhanca.onrender.com/api/v1/resident/62
Authorization: Bearer {{token}}


### ===== PUBLICATION =====
# @name listPublication
GET http://localhost:8080/api/v1/publication
Authorization: Bearer {{token}}

### Insert
# @name insertPublication
POST http://localhost:8080/api/v1/publication
Authorization: Bearer {{token}}
Content-Type: application/json