@token = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0ZUB0ZXN0ZS5jb20iLCJpYXQiOjE3NzgxMjAyNzksImV4cCI6MTc3ODIwNjY3OX0.FIwf6U9zYlY3fp48-EwNg7lPJVrz6r7U4wUC6am-F3U
### LoginCondominium
# @name loginRequest
POST http://localhost:8080/api/v1/auth/login/condominium
Content-Type: application/json

{
  "email": "teste@teste.com",
  "password": "OiCamila"
}

### LoginResident
# @name loginRequest
POST http://localhost:8080/api/v1/auth/login/resident
Content-Type: application/json

{
"email": "leonardo07@gmail.com",
"password": "k#x8Wb9!"
}



### ===== CONDOMINIUM =====
# @name listCondominium
GET http://localhost:8080/api/v1/condominium
Authorization: Bearer {{token}}

### Search by id
# @name searchCondominium
GET http://localhost:8080/api/v1/condominium/1
Authorization: Bearer {{token}}

### Insert
# @name insertCondominium
POST http://localhost:8080/api/v1/condominium
Content-Type: application/json

{
    "name": "Boa Vista",
    "cnpj": "12345678910110",
    "amount_blocks": 4,
    "amount_apartments": 160,
    "email": "teste@teste.com",
    "password": "OiCamila"
}

### Update
# @name updateCondominium
PUT http://localhost:8080/api/v1/condominium/7
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Bela Vista",
  "cnpj": "12345678910124",
  "amount_blocks": 4,
  "amount_apartments": 160,
  "email": "contato@scotti.com.br"
}

### Delete
# @name deleteCondominium
DELETE http://localhost:8080/api/v1/condominium/11
Authorization: Bearer {{token}}


### ===== RESIDENT =====
# @name listResident
GET http://localhost:8080/api/v1/resident
Authorization: Bearer {{token}}

### Search by ID
# @name searchResident
GET http://localhost:8080/api/v1/resident/6
Authorization: Bearer {{token}}

### Insert
# @name insertResident
POST http://localhost:8080/api/v1/resident
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "photo": "",
  "name": "Roger",
  "apartment": "1",
  "block": "Torre 1",
  "cpf": "42969976889",
  "email": "leonardo@gmail.com",
  "phone": "11998572585",
  "score": 0,
  "condominium_id": 1
}

### Update
# @name updateResident
PUT http://localhost:8080/api/v1/resident/
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "foto": "",
    "nome": "Leonardo",
    "apto": "82",
    "bloco": "Torre 2",
    "cpf": "67890123456",
    "email": "ricardo.santos@yahoo.com",
    "telefone": "11943210987",
    "pontuacao": 20,
    "condominium_id": 5
}