spring.application.name=vizinhanca

# JWT
jwt.secret=vizinhanca-secret-key-super-segura-2026

# Server
server.port=8080

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/NOME_DO_SEU_BANCO?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=SEU_USUARIO
spring.datasource.password=SUA_SENHA

# JPA
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true