spring.application.name=vizinhanca

# JWT
jwt.secret=Uma-SENHA-qualQUER-doGrupO-VIZInhanca

# SERVER
server.port=${PORT:8080}

# MySQL
spring.datasource.url=jdbc:mysql://mysql-giovana.mysql.database.azure.com:3306/db_tcc_vizinhanca?useSSL=true&allowPublicKeyRetrieval=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=apiuser
spring.datasource.password=VizinhancaSENAI@2026

# JPA
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# SWAGGER
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.operations-sorter=alpha

# GMAIL
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=leonardo.scotti07@gmail.com
spring.mail.password=dall gytv hxci flkz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

DB_PASS=VizinhancaSENAI@2026
DB_URL=jdbc:mysql://mysql-giovana.mysql.database.azure.com:3306/db_tcc_vizinhanca?useSSL=true&allowPublicKeyRetrieval=true
DB_USER=apiuser
JWT_SECRET=Uma-SENHA-qualQUER-doGrupO-VIZInhanca