spring.application.name=vizinhanca

# JWT
jwt.secret=${JWT_SECRET}

# SERVER
server.port=${PORT:8080}

# MySQL
spring.datasource.url=${DB_URL}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

# JPA
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# SWAGGER
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.operations-sorter=alpha

# MAIL
azure.communication.connection-string=${AZURE_MAIL_KEY}
azure.communication.sender=${AZURE_MAIL_SENDER}

# CACHE
spring.cache.type=caffeine
spring.cache.caffeine.spec=maximumSize=500,expireAfterWrite=10m